server: 
  port: 80
  servlet: 
   context-path: /enjoytrip 

spring: 
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/enjoytrip?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    hikari:
      username: ssafy
      password: ssafy
      
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml